# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-23 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranges', models.CharField(blank=True, max_length=255, null=True, verbose_name='审批时长')),
            ],
            options={
                'verbose_name_plural': '审批时长表',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='渠道备注')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='渠道名称')),
            ],
            options={
                'verbose_name_plural': '渠道信息表',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_low', models.CharField(blank=True, max_length=255, null=True, verbose_name='最低月利率')),
                ('month_high', models.CharField(blank=True, max_length=255, null=True, verbose_name='最高月利率')),
            ],
            options={
                'verbose_name_plural': '月利率表',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_low', models.CharField(blank=True, max_length=255, null=True, verbose_name='最低额度')),
                ('position_high', models.CharField(blank=True, max_length=255, null=True, verbose_name='最高额度')),
            ],
            options={
                'verbose_name_plural': '贷款额度表',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='机构介绍')),
                ('product_icon', models.FileField(blank=True, null=True, upload_to='media/upload', verbose_name='产品图标')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品名称')),
                ('product_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='放款人数')),
                ('approve_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Approve', verbose_name='审批时长')),
                ('month_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Month', verbose_name='月利率')),
                ('position_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Position', verbose_name='额度范围')),
            ],
            options={
                'verbose_name_plural': '客户信息表',
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_low', models.CharField(blank=True, max_length=255, null=True, verbose_name='最低期限')),
                ('time_high', models.CharField(blank=True, max_length=255, null=True, verbose_name='最高期限')),
            ],
            options={
                'verbose_name_plural': '贷款期限表',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='唯一标识')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='手机号')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('age', models.CharField(blank=True, max_length=255, null=True, verbose_name='年龄')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='家庭住址')),
                ('card_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='身份证号')),
                ('position_range', models.CharField(blank=True, max_length=255, null=True, verbose_name='贷款额度')),
                ('time_range', models.CharField(blank=True, max_length=255, null=True, verbose_name='贷款期限')),
                ('reg_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Channel', verbose_name='所属渠道')),
            ],
            options={
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='time_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Timer', verbose_name='期限范围'),
        ),
    ]
